# Generated by Django 3.0.3 on 2020-10-07 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='tweet',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
